In [27]:
g = list(range(10))
print(g)
sum(g)
#%timeit sum(g)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


45

In [28]:
# Python don't have array by default. It has list. Normal + operator will concat 2 lists
a = [10,12,14,16]
b = [1,2,3,4]
a+b

[10, 12, 14, 16, 1, 2, 3, 4]

In [10]:
import numpy as np
%timeit np.sum(g)

5.55 µs ± 69.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [35]:
# NumPy Array in Python
a = np.array([10,12,14,16])
print (a)
b= np.array([1,2,3,45])
# Add 2 numPy Array. In this case it will add but in this case both the array should have same number of elements.
a+b

[10 12 14 16]


array([11, 14, 17, 61])

In [41]:
#Check the type of Array in Numpy.
#ndarray stands for "n dimesional array"
type(a)

numpy.ndarray

In [43]:
#Check the dimesion of array
a.ndim

1

In [45]:
#Shape of the array
#Shape returns the tuple listing the length of elements array in each dimension
a.shape

(4,)

In [47]:
# Bytes per element
a.itemsize

4

In [49]:
# Bytes of memory used
# returns the number of bytes used by the data portion of the Array
a.nbytes

16

In [51]:
#Check the Datatyes Of the Array
a.dtype

dtype('int32')

In [54]:
# Array Indexing
print(a[0])
a[0] = 100
print(a)
a[0] = 19.90
print(a[0])

100
[100  12  14  16]
19


In [66]:
#NumPy decide the data type of the array depending on the element present in it.
# For example a=[10,20,30,40,5]. In this one element is float so the data type of the array is float.
a=np.array([10,20,30,40.5])
print(a.dtype)

#datatype of the array can be changed forcefully by providing the dtype in the array
a= np.array([10,20,30,40.5],dtype='int64')
print(a.dtype)

#The elements in the array after changing the datatype will looks like as [10 20 30 40]
print(a)
a

float64
int64
[10 20 30 40]


array([10, 20, 30, 40], dtype=int64)